//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NorthWindEntities : DbContext
    {
        public NorthWindEntities()
            : base("name=NorthWindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<CartContent> spGetCart(Nullable<int> cart)
        {
            var cartParameter = cart.HasValue ?
                new ObjectParameter("Cart", cart) :
                new ObjectParameter("Cart", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CartContent>("spGetCart", cartParameter);
        }
    }
}
