CREATE TABLE dbo.Users
	(
	id numeric(18, 0) NOT NULL IDENTITY (1, 1),
	username nvarchar(50) NOT NULL,
	Password nchar(20) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Users ADD CONSTRAINT
	PK_Table_1 PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
